### ISSUE TITLE
Getting the following error using Serilog.Settings.Configuration

### ISSUE THREAD

**Issue by jwebber974** [serilog/serilog-settings-configuration#119]
Hello,

We are using the configuration library with a asp.net core 2.1 app and we are getting the following error when we try to build the logging configuration:

This is how we are building the configuration:

var configuration = new ConfigurationBuilder()
            .SetBasePath(Directory.GetCurrentDirectory())
            .AddJsonFile("appsettings.json")
            .Build();

            var assemblyInfo = Assembly.GetEntryAssembly().GetName();
            Log.Logger = new LoggerConfiguration()
                .ReadFrom.Configuration(configuration)
                .MinimumLevel.Verbose()
                .Enrich.WithProcessId()
                .Enrich.WithEnvironmentUserName()
                .Enrich.WithMachineName()
                .Enrich.WithThreadId()
                .Enrich.WithProperty("ApplicationName", assemblyInfo.Name)
                .Enrich.WithProperty("Version", assemblyInfo.Version.ToString())
                .Enrich.FromLogContext()
                .CreateLogger();

This is the error:

Application: Integration.WebApi.exe
CoreCLR Version: 4.6.26606.2
Description: The process was terminated due to an unhandled exception.
Exception Info: System.TypeLoadException: Could not load type 'System.Web.IHttpModule' from assembly 'System.Web, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
   at System.Reflection.RuntimeAssembly.GetExportedTypes(RuntimeAssembly assembly, ObjectHandleOnStack retTypes)
   at System.Reflection.RuntimeAssembly.GetExportedTypes()
   at Serilog.Settings.Configuration.ConfigurationReader.<>c.<FindConfigurationMethods>b__23_0(Assembly a)
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Serilog.Settings.Configuration.ConfigurationReader.FindEventEnricherConfigurationMethods(IReadOnlyCollection`1 configurationAssemblies)
   at Serilog.Settings.Configuration.ConfigurationReader.ApplyEnrichment(LoggerConfiguration loggerConfiguration, IReadOnlyDictionary`2 declaredLevelSwitches)
   at Serilog.Settings.Configuration.ConfigurationReader.Configure(LoggerConfiguration loggerConfiguration)
   at Serilog.Configuration.LoggerSettingsConfiguration.Settings(ILoggerSettings settings)
   at Integration.WebApi.Program.Main(String[] args) in C:\src\igsolutions_repo\Code\Integration.WebApi\Program.cs:line 21

**Comment by tsimbalar** [comment]
Hi Jeff,

could you also post the contents of your `appsettings.json` file please ?

**Comment by jwebber974** [comment]
Sure thing. Here it is.

![image](https://user-images.githubusercontent.com/4732666/42403063-7eb80c00-8133-11e8-9f90-8b6c08b4cef3.png)

**Comment by tsimbalar** [comment]
Are you by any chance referencing any *System.Web* dependent libraries in your project ? I am not sure this can work in a ASP.NET Core app.

The error message `Could not load type 'System.Web.IHttpModule' from assembly 'System.Web, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
at System.Reflection.RuntimeAssembly.GetExportedTypes(RuntimeAssembly assembly, ObjectHandleOnStack retTypes)` is suspicious :P .

**Comment by jwebber974** [comment]
I think you are correct. There were a couple project references to .NET FX projects and when I removed them, the error went away. Seems like a .NET framework to Core compatibility issue. I'll close it out.

**Comment by tsimbalar** [comment]
Thanks for the feedback, Jeff 👍
