### ISSUE TITLE
Readme.md docs don't work and throw InvalidCastException 

### ISSUE THREAD

**Issue by CreepyGnome** [serilog/serilog-settings-configuration#194]
Created a clean .NET Core console app. Followed the readme.md doc and Configuration extension method used has such `ReadFrom.Configuration(configuration)` throws System.InvalidCastException.

`System.InvalidCastException
  HResult=0x80004002
  Message=Invalid cast from 'System.String' to 'Serilog.Core.IDestructuringPolicy'.
  Source=System.Private.CoreLib
  StackTrace:
   at System.Convert.DefaultToType(IConvertible value, Type targetType, IFormatProvider provider)
   at Serilog.Settings.Configuration.StringArgumentValue.ConvertTo(Type toType, ResolutionContext resolutionContext)
   at Serilog.Settings.Configuration.ConfigurationReader.<>c__DisplayClass18_2.<CallConfigurationMethods>b__3(<>f__AnonymousType9`2 <>h__TransparentIdentifier0)
   at System.Linq.Utilities.<>c__DisplayClass2_0`3.<CombineSelectors>b__0(TSource x)
   at System.Linq.Enumerable.SelectListPartitionIterator`2.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Serilog.Settings.Configuration.ConfigurationReader.CallConfigurationMethods(ILookup`2 methods, IList`1 configurationMethods, Object receiver)
   at Serilog.Settings.Configuration.ConfigurationReader.Configure(LoggerConfiguration loggerConfiguration)
   at Serilog.Configuration.LoggerSettingsConfiguration.Settings(ILoggerSettings settings)
   at FunWithSerilogNetCore.Program.Main(String[] args) in C:\src\Playgroud\FunWithSerilogNetCore\Program.cs:line 15`

If I remove the Destructure property from the appsettings.json it works.

See the attached project for example.

[FunWithSerilogNetCore.zip](https://github.com/serilog/serilog-settings-configuration/files/3503417/FunWithSerilogNetCore.zip)

So if you could fix the readme.md so that the code will work maybe just remove the json property that it is failing on or better yet add what is missing so that it works with that json file.

**Comment by nblumhardt** [comment]
Thanks for the note, we'll check it out

**Comment by UltimateForm** [comment]
This was fixed? How? I still get the same error, and the message is still the same....

**Comment by nblumhardt** [comment]
@UltimateForm are you running the latest `-dev*` version of the package?

**Comment by UltimateForm** [comment]
@nblumhardt no, just the nuget release, thought this fix had been released already, my bad 🙏

**Comment by nblumhardt** [comment]
The `-dev*` packages are on NuGet, too: https://www.nuget.org/packages/Serilog.Settings.Configuration/3.2.0-dev-00272
