### ISSUE TITLE
Samples are broken out of the box

### ISSUE THREAD

**Issue by mwpowellhtx** [serilog/serilog-settings-configuration#227]
I copied the Sample out of the box virtually verbatim, substituting `netcoreapp3.1` for the multiple targets and a true package reference for the project reference. I got the following exception.

What am I missing here?

```
System.ArgumentException
  HResult=0x80070057
  Message=Configuration for Action<Serilog.Configuration.LoggerEnrichmentConfiguration> is not implemented.
  Source=Serilog.Settings.Configuration
  StackTrace:
   at Serilog.Settings.Configuration.ObjectArgumentValue.ConvertTo(Type toType, ResolutionContext resolutionContext)
   at Serilog.Settings.Configuration.ConfigurationReader.<>c__DisplayClass18_2.<CallConfigurationMethods>b__3(<>f__AnonymousType9`2 <>h__TransparentIdentifier0)
   at System.Linq.Utilities.<>c__DisplayClass2_0`3.<CombineSelectors>b__0(TSource x)
   at System.Linq.Enumerable.SelectListPartitionIterator`2.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Serilog.Settings.Configuration.ConfigurationReader.CallConfigurationMethods(ILookup`2 methods, IList`1 configurationMethods, Object receiver)
   at Serilog.Settings.Configuration.ConfigurationReader.ApplyEnrichment(LoggerConfiguration loggerConfiguration)
   at Serilog.Settings.Configuration.ConfigurationReader.Configure(LoggerConfiguration loggerConfiguration)
   at Serilog.Configuration.LoggerSettingsConfiguration.Settings(ILoggerSettings settings)
   at Serilog.ConfigurationLoggerConfigurationExtensions.Configuration(LoggerSettingsConfiguration settingConfiguration, IConfiguration configuration, String sectionName, DependencyContext dependencyContext)
   at Serilog.ConfigurationLoggerConfigurationExtensions.Configuration(LoggerSettingsConfiguration settingConfiguration, IConfiguration configuration, DependencyContext dependencyContext)
   at Sample.Program.Main(String[] args) in \path\to\Sample\Program.cs:line 25
```

With the `.csproj`:

```Xml
<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>netcoreapp3.1</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Serilog.Sinks.Async" Version="1.4" />
        <PackageReference Include="Serilog.Settings.Configuration" Version="3.1" />
        <PackageReference Include="Serilog.Sinks.Console" Version="3.1.1" />
        <PackageReference Include="Serilog.Sinks.File" Version="4.1" />
        <PackageReference Include="Serilog.Enrichers.Environment" Version="2.1.3" />
        <PackageReference Include="Serilog.Enrichers.Process" Version="2.0.1" />
        <PackageReference Include="Serilog.Enrichers.Thread" Version="3.1" />
        <PackageReference Include="Serilog.Filters.Expressions" Version="2.1" />
        <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="2.0.1" />
    </ItemGroup>

    <ItemGroup>
        <None Update="appsettings.json">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
    </ItemGroup>

</Project>
```

**Comment by skomis-mm** [comment]
Hi @mwpowellhtx ,

If you use v`3.1` try to get the sample from the `master` branch:
https://github.com/serilog/serilog-settings-configuration/blob/master/sample/Sample/appsettings.json

**Comment by mwpowellhtx** [comment]
The error I am receiving [jives with an older version](https://github.com/serilog/serilog-settings-configuration/commit/801d6d85cfae98d6e19d69ade439ac866844f622#diff-6940a2e06a5cf00461ee3a198b259c07L35) of the code, I think, which beggars the question, is there a release version coming?

**Comment by mwpowellhtx** [comment]
@skomis-mm Ah, yes, that does explain that. Obviously these are "dev" releases; are they stable-ish? Elsewise, when we might expect a proper release? Thanks...

**Comment by mwpowellhtx** [comment]
Thanks again, over the hump for the moment.

**Comment by skomis-mm** [comment]
@mwpowellhtx  It should be stable enough. Would be great if you try the `dev` releases.
