### ISSUE TITLE
AssemblyFinder throw Exception in .Net5.0(RC2) SingleFile

### ISSUE THREAD

**Issue by xljiulang** [serilog/serilog-settings-configuration#239]
Unhandled exception. System.NotSupportedException: CodeBase is not supported on assemblies loaded from a single-file bundle.
   at System.Reflection.RuntimeAssembly.get_CodeBase()
   at Microsoft.Extensions.DependencyModel.DependencyContextLoader.GetNormalizedCodeBasePath(Assembly assembly)
   at Microsoft.Extensions.DependencyModel.DependencyContextLoader.GetDepsJsonPath(Assembly assembly)
   at Microsoft.Extensions.DependencyModel.DependencyContextLoader.LoadAssemblyContext(Assembly assembly, IDependencyContextReader reader)
   at Microsoft.Extensions.DependencyModel.DependencyContextLoader.Load(Assembly assembly)
   at Microsoft.Extensions.DependencyModel.DependencyContext.Load(Assembly assembly)
   at Microsoft.Extensions.DependencyModel.DependencyContext.LoadDefault()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.get_Value()
   at Microsoft.Extensions.DependencyModel.DependencyContext.get_Default()
   at Serilog.Settings.Configuration.Assemblies.AssemblyFinder.Auto()
   at Serilog.ConfigurationLoggerConfigurationExtensions.Configuration(LoggerSettingsConfiguration settingConfiguration, IConfiguration configuration, String sectionName, DependencyContext dependencyContext)
   at Serilog.ConfigurationLoggerConfigurationExtensions.Configuration(LoggerSettingsConfiguration settingConfiguration, IConfiguration configuration, DependencyContext dependencyContext)
   at HostApp.Program.<>c.<CreateHostBuilder>b__1_2(WebHostBuilderContext hosting, LoggerConfiguration logger)
   at Serilog.SerilogWebHostBuilderExtensions.<>c__DisplayClass1_0.<UseSerilog>b__0(WebHostBuilderContext context, IServiceCollection collection)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass11_0.<ConfigureServices>b__0(HostBuilderContext context, IServiceCollection builder)
   at Microsoft.Extensions.Hosting.HostBuilder.CreateServiceProvider()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
   at HostApp.Program.Main(String[] args)

**Comment by nblumhardt** [comment]
Thanks for letting us know 👍

**Comment by BalintBanyasz** [comment]
This seems to be related: [https://github.com/dotnet/runtime/issues/41265](https://github.com/dotnet/runtime/issues/41265)

@nblumhardt Do you think that it can be fixed in Serilog.Settings.Configuration? Currently this is the only thing preventing me from upgrading my SingleFile WinForms App from .NET Core 3.1 to .NET 5.0. Thanks!

**Comment by nblumhardt** [comment]
Hi @BalintBanyasz - thanks for the note. Yes, I'd guess there is some way to detect this situation and avoid a crash, here. I am short of time to investigate at the moment; if anyone encountering this has time to debug and propose a fix, that would be welcome.

**Comment by tsimbalar** [comment]
In the meantime, you can maybe provide your own implementation of `DependencyContext` in the call to `ReadFrom.Configuration(...)` as a workaround ?

**Comment by murugaratham** [comment]
tried implementing

```cs
var functionDependencyContext = DependencyContext.Load(typeof(Startup).Assembly);
...
.ReadFrom.Configuration(configuration, "Serilog", dependencyContext: functionDependencyContext)
```
but still getting hit with

```
Unhandled exception. System.NotSupportedException: CodeBase is not supported on assemblies loaded from a single-file bundle.
   at System.Reflection.RuntimeAssembly.get_CodeBase()
   at Microsoft.Extensions.DependencyModel.DependencyContextLoader.GetNormalizedCodeBasePath(Assembly assembly)
   at Microsoft.Extensions.DependencyModel.DependencyContextLoader.GetDepsJsonPath(Assembly assembly)
   at Microsoft.Extensions.DependencyModel.DependencyContextLoader.LoadAssemblyContext(Assembly assembly, IDependencyContextReader reader)
   at Microsoft.Extensions.DependencyModel.DependencyContextLoader.Load(Assembly assembly)
   at Microsoft.Extensions.DependencyModel.DependencyContext.Load(Assembly assembly)
   at xxxx.Api.Program.CreateSerilogLogger(IConfiguration configuration)
   at xxxx.Api.Program.Main(String[] args)
```

**Comment by skomis-mm** [comment]
Hi guys, the current workaround for v3.1 is to use
```csharp
.ReadFrom.Configuration(configuration, ConfigurationAssemblySource.AlwaysScanDllFiles)
```
and place all external configuration assemblies to `Using` section:
```json
"Using": [ "Serilog.Sinks.Console", "Serilog.Enrichers.Thread", ... etc ],
```
I've added NotSupportedException handling to the PR and updated the documentation.

**Comment by murugaratham** [comment]
any workaround for .net 5?

**Comment by skomis-mm** [comment]
@murugaratham sorry, I meant `Serilog.Settings.Configuration` 3.1.0

**Comment by murugaratham** [comment]
@skomis-mm yea, i am on .net 5 and i've tried `.ReadFrom.Configuration(configuration, ConfigurationAssemblySource.AlwaysScanDllFiles)` and also specifying using 
```
"Serilog": {
    "Using": [
      "Serilog.Sinks.Console",
      "Serilog.Sinks.File",
      "Serilog.Sinks.File"
    ]
...
```

but i still get [same](https://github.com/serilog/serilog-settings-configuration/issues/239#issuecomment-728906156) error

**Comment by skomis-mm** [comment]
@murugaratham , interesting. Do you have any `DependencyContext` usage left in the code?

```
at Microsoft.Extensions.DependencyModel.DependencyContext.Load(Assembly assembly)
at xxxx.Api.Program.CreateSerilogLogger(IConfiguration configuration)
```
Are the any stack frames between these 2 lines?

**Comment by murugaratham** [comment]
The stack trace pasted was pretty much it

**Comment by skomis-mm** [comment]
```csharp
var functionDependencyContext = DependencyContext.Load(typeof(Startup).Assembly);
...
.ReadFrom.Configuration(configuration, "Serilog", dependencyContext: functionDependencyContext)
```
Is the `DependencyContext.Load` called from `CreateSerilogLogger(..)` ?

**Comment by murugaratham** [comment]
Yup, here's a screenshot of the source

![Screenshot 2020-11-18 at 9 21 04 AM](https://user-images.githubusercontent.com/653805/99470298-76769380-297f-11eb-9404-574828724e4e.png)

Here's the log's after publishing as SingleFile & PublishTrimmed
![Screenshot 2020-11-18 at 9 20 44 AM](https://user-images.githubusercontent.com/653805/99470371-97d77f80-297f-11eb-9ad4-d0c778497be5.png)

**Comment by skomis-mm** [comment]
@murugaratham just remove this line
`var functionDependencyContext = DependencyContext.Load(typeof(Startup).Assembly);`

**Comment by murugaratham** [comment]
Seems working fine and I feel dumb

**Comment by eLPe21** [comment]
Not sure if this is related, but when I build to single file for Centos7 ( the build is done on Mac ) 
I get extra files that I have to send over to make the application working: 

The files are added to the publish folder as soon as I add Serilog.Settings.Configuration on my net50 project. 

```
../out50/System.Native.a			
../out50/System.Native.so			
../out50/System.Security.Cryptography.Native.so
```

**Comment by nathanpovo** [comment]
Another workaround is to set `IncludeAllContentForSelfExtract` to `true` when publishing. Setting this property to true changes the `.NET 5.0` system of single-file apps to be backward compatible with the `.NET Core 3.x` system (as described [here](https://github.com/dotnet/designs/blob/main/accepted/2020/single-file/design.md#optional-settings)).

Some additional info on the workaround can be found here - https://github.com/dotnet/runtime/issues/44511#issuecomment-725253197
Related issue - https://github.com/dotnet/runtime/issues/42265

**Comment by sungam3r** [comment]
Would be nice to mention it in the readme.
