### ISSUE TITLE
Exception when using Fody/Anotar

### ISSUE THREAD

**Issue by KevinGliewe** [serilog/serilog-settings-configuration#303]
# Description

There is a `System.IO.FileNotFoundException` Exception when using `Serilog.Settings.Configuration` together with [`Fody/Anotar`](https://github.com/Fody/Anotar):

```text
Unhandled exception. System.IO.FileNotFoundException: Could not load file or assembly 'Anotar.Serilog, Culture=neutral, PublicKeyToken=null'. Das System kann die angegebene Datei nicht finden.
File name: 'Anotar.Serilog, Culture=neutral, PublicKeyToken=null'
   at System.Reflection.RuntimeAssembly.InternalLoad(ObjectHandleOnStack assemblyName, ObjectHandleOnStack requestingAssembly, StackCrawlMarkHandle stackMark, Boolean throwOnFileNotFound, ObjectHandleOnStack assemblyLoadContext, ObjectHandleOnStack retAssembly)
   at System.Reflection.RuntimeAssembly.InternalLoad(AssemblyName assemblyName, RuntimeAssembly requestingAssembly, StackCrawlMark& stackMark, Boolean throwOnFileNotFound, AssemblyLoadContext assemblyLoadContext)
   at System.Reflection.Assembly.Load(AssemblyName assemblyRef)
   at Serilog.Settings.Configuration.ConfigurationReader.LoadConfigurationAssemblies(IConfigurationSection section, AssemblyFinder assemblyFinder)
   at Serilog.Settings.Configuration.ConfigurationReader..ctor(IConfigurationSection configSection, AssemblyFinder assemblyFinder, IConfiguration configuration)
   at Serilog.ConfigurationLoggerConfigurationExtensions.Configuration(LoggerSettingsConfiguration settingConfiguration, IConfiguration configuration, String sectionName, DependencyContext dependencyContext)
   at Serilog.ConfigurationLoggerConfigurationExtensions.Configuration(LoggerSettingsConfiguration settingConfiguration, IConfiguration configuration, DependencyContext dependencyContext)
   at Program.<Main>$(String[] args) in #ProjectPath#\Program.cs:line 8
```

The `ConfigurationReader` trys to load all assemblies containing the name "serilog" and referencing serilog:

## Inside `ConfigurationReader.LoadConfigurationAssemblies(...)`

```c#
foreach (var assemblyName in assemblyFinder.FindAssembliesContainingName("serilog"))
```

## Inside `DependencyContextAssemblyFinder.FindAssembliesContainingName(...)`

```c#
var query = from library in _dependencyContext.RuntimeLibraries
            where IsReferencingSerilog(library)
            from assemblyName in library.GetDefaultAssemblyNames(_dependencyContext)
            where IsCaseInsensitiveMatch(assemblyName.Name, nameToFind)
            select assemblyName;
```

This clashes with Anotar, since the refenrence to the assembly `Anotar.Serilog` is ony used during buildtime and is not present at runtime. (At least this is what i think what happens)

As far as i can tell, there is no way to prevent assemblies from getting automaticly loaded?

# Minimal repo

I created a minimal repo with additional informations:

[https://github.com/KevinGliewe/Anotar.Serilog.Issue](https://github.com/KevinGliewe/Anotar.Serilog.Issue)

**Comment by KevinGliewe** [comment]
OK, i didn't notice you can pass an custom `DependencyContext` into the configurator. This way it is possible to filter Anotar.Serilog.Fody from the runtime libraries:

````c#
// Initialize Logging
new LoggerConfiguration()
    .ReadFrom.Configuration(config, "Serilog", new DependencyContextFilter(Microsoft.Extensions.DependencyModel.DependencyContext.Default));

// Custom DependencyContext without Anotar.Serilog.Fody
class DependencyContextFilter : Microsoft.Extensions.DependencyModel.DependencyContext
{
    public DependencyContextFilter(Microsoft.Extensions.DependencyModel.DependencyContext other) : 
        base(other.Target, other.CompilationOptions, other.CompileLibraries, other.RuntimeLibraries.Where(rl => rl.Name != "Anotar.Serilog.Fody"), other.RuntimeGraph)
    {
    }
}
````
