### ISSUE TITLE
Could not load file or assembly serilog.sinks.mssqlservercore

### ISSUE THREAD

**Issue by itlackey** [serilog/serilog-settings-configuration#39]
Hello, any help with this is much appreciated. I am trying to use the appsettings file to configure Serilog while using the Core port of the MSSqlServer sink. Every time I add ReadFrom.Configuration I receive the exception posted below. This happens even if I do not reference the MSSqlServer sink in the appsettings or in the startup code. Any ideas on how to get past this?

TIA!

 ---
System.IO.FileNotFoundException occurred
  HResult=0x80070002
  Message=Could not load file or assembly 'serilog.sinks.mssqlservercore, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
  Source=<Cannot evaluate the exception source>
  StackTrace:
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks, IntPtr ptrLoadContextBinder)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks, IntPtr ptrLoadContextBinder)
   at System.Reflection.Assembly.Load(AssemblyName assemblyRef)
   at Serilog.Settings.Configuration.ConfigurationReader.LoadConfigurationAssemblies()
   at Serilog.Settings.Configuration.ConfigurationReader.Configure(LoggerConfiguration loggerConfiguration)
   at Serilog.Configuration.LoggerSettingsConfiguration.Settings(ILoggerSettings settings)
   at Gozer.Startup.ConfigureServices(IServiceCollection services) in

**Comment by skomis-mm** [comment]
@itlackey , thanks for the info, seems like a bug. The problem is that package name is not the same as configuration assembly name.

**Comment by itlackey** [comment]
Wow, you all are fast! Thanks for taking care of this so quickly!
