### ISSUE TITLE
Unable to run Sample when changing target to ASP.NET Core 1.1

### ISSUE THREAD

**Issue by chromefox** [serilog/serilog-settings-configuration#59]
Hi,

**Issue**
I am attempting to define multiple loggers similar to what your Sample has done. However, I am unable to run it when I changed the target to asp.net core 1.1.

**Details**
I have reproduced the issue in this repo https://github.com/chromefox/serilog-json

What I have done is simply:

1. Change the sdk to target Web on .csproj
2. Change the target to target a single framework, i.e. netcoreapp1.1
3. Copy the code to Startup.cs and add a Kestrel bootstrap in Program.cs
4. Run the application via dotnet run, following dotnet restore.

It will throw the following exception:

```
Unhandled Exception: System.ArgumentNullException: Value cannot be null.
Parameter name: name
   at System.Environment.ExpandEnvironmentVariables(String name)
   at Serilog.Settings.Configuration.ConfigurationReader.GetMethodCalls(IConfigurationSection directive)
   at Serilog.Settings.Configuration.ConfigurationReader.ApplySinks(LoggerConfiguration loggerConfiguration, Assembly[] configurationAssemblies)
   at Serilog.Configuration.LoggerSettingsConfiguration.Settings(ILoggerSettings settings)
   at Sample.Startup..ctor(IHostingEnvironment env) in \serilog-settings-configuration-dev\serilog-settings-configuration-dev\sample\Sample\Startup.cs:line 26
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Extensions.Internal.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
   at Microsoft.AspNetCore.Hosting.Internal.StartupLoader.LoadMethods(IServiceProvider hostingServiceProvider, Type startupType, String environmentName)
   at Microsoft.AspNetCore.Hosting.WebHostBuilderExtensions.<>c__DisplayClass1_0.<UseStartup>b__1(IServiceProvider sp)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.<>c__DisplayClass16_0.<RealizeService>b__0(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureStartup()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureApplicationServices()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
```

**Comment by merbla** [comment]
Hi @chromefox,

With your sample, removing the following [line](https://github.com/chromefox/serilog-json/blob/master/Startup.cs#L23) seemed to do the trick.

Did you have an optional file you were using to configure the app?

HTH

**Comment by chromefox** [comment]
Hi,

Thanks for the swift reply.

I tried removing the line on my own environment, but the same error still persists on my side.

The optional file, which I didn't commit, is just a Visual Studio generated file with the following content:
```
{
  "Logging": {
    "IncludeScopes": false,
    "LogLevel": {
      "Default": "Debug",
      "System": "Information",
      "Microsoft": "Information"
    }
  }
}
```

**Comment by skomis-mm** [comment]
@chromefox, try update the package to [2.4.0](https://www.nuget.org/packages/Serilog.Settings.Configuration/2.4.0) version.

**Comment by nblumhardt** [comment]
If the issue still persists in 2.4 please reopen.
